# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/jichuang/fpga/digital_twin/digital_twin.srcs/sources_1/ip/irom_ip/irom_ip.xci
# IP: The module: 'irom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/jichuang/fpga/digital_twin/digital_twin.gen/sources_1/ip/irom_ip/irom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/jichuang/fpga/digital_twin/digital_twin.srcs/sources_1/ip/irom_ip/irom_ip.xci
# IP: The module: 'irom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/jichuang/fpga/digital_twin/digital_twin.gen/sources_1/ip/irom_ip/irom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
